### ISSUE TITLE
breakdown schets

### ISSUE THREAD

**Issue by nadiachaja** [nadiachaja/look-and-feel-corporate-identity#2]
![Media](https://github.com/user-attachments/assets/9ce78901-00ad-47a8-898f-aa468b356c92)

**Comment by Yu-Jing-van-Gerwen** [comment]
Je schets is duidelijk en overzichtelijk zet er nog een `main` in na de body en `section` dus section en dan h2 en p

het blok privacy statement zou ik ook als section doen dus die paarse pijltjes die ik erbij gezet heb



![image](https://github.com/user-attachments/assets/e61601a6-8d99-4ca3-9ce1-5a6d13868d77)

heb je ook bedacht hoe je dit responsive gaat maken?

en heb je bedacht hoe je deze 2 tekst blokjes naast elkaar gaat zetten met css ?

![image](https://github.com/user-attachments/assets/ac4c86b2-d00f-4a51-9324-412be5f61fe4)

ik denk dat het handig is om een aparte css schets te maken waarin je benoemend hoe je dit gaat realiseren of met een andere kleur dit gaat toevoegen aan deze schets

**Comment by nadiachaja** [comment]
Ik heb een css schets gemaakt. 
![testing css](https://github.com/user-attachments/assets/66a2013f-cfcd-42e5-8fe8-65ddeddc5150) 

Ik heb de section toegevoegd aan de breakdown schets van de html 
![testing html nieuwe](https://github.com/user-attachments/assets/6eaf519e-8fff-4cf4-bc01-a67ce4fe6ab4)


Ik heb nagedacht over hoe ik het responsive te maken ik ga @media gebruiken. 
Daarnaast heb ik gekeken hoe ik de 2 tekst blokje naast elkaar zet. Ik ga flex gebruiken.
